### ISSUE TITLE
可以上傳 hdf5檔和selenium最後測試使用之程式碼嗎

### ISSUE THREAD

**Issue by lukedoomer** [gary9987/keras-TaiwanHighSpeedRail-captcha#1]
hdf5檔從您程式碼看到的路徑是model/cnn_model.hdf5
selenium的話readme有提到但是code沒看到
方便的話麻煩大大上傳 跳過手動標記的痛苦 XD

**Comment by gary9987** [comment]
抱歉，這麼久才看到。 我已經有一段時間沒使用，不確定提供的是不是你需要的。
不確定高鐵網站架構是否修改過，希望新上傳的東西有幫助到你。
