### ISSUE TITLE
詢問操作方法以及最終程式碼

### ISSUE THREAD

**Issue by Roy1109** [gary9987/keras-TaiwanHighSpeedRail-captcha#2]
您好，最近看到你提供的高鐵驗證碼的開源碼。
但是由於不太會操作你提供的資料夾和資料集，可以請問要如何操作和使用嗎?
並且可以提供一下最後訓練和測試的程式碼嗎?因為目前去使用好像有點問題，沒辦法跑出和你提供的結果類似的檔案。

謝謝

**Comment by gary9987** [comment]
我已經將資訊更新在README.md，謝謝。

**Comment by Roy1109** [comment]
> 我已經將資訊更新在README.md，謝謝。

謝謝你的更新，這給予很大的幫助
